#!/bin/bash

CCF=gcc-7
CFLAGS='-O2 -Wall'
LDFLAGS='-lncurses -L. -Iinclude'



# Covert C files to .o files
$CCF $CFLAGS $LDFLAGS -c *.c

# Compile programme
$CCF $CFLAGS $LDFLAGS -o ztorg *.o

# Remove .o files
rm *.o