#!/bin/bash

CCF=gcc-7
CFLAGS='-Wall'
LDFLAGS='-lncurses -L. -Iinclude'

OUTEX_FILE='z'

# Covert C files to .o files
$CCF $CFLAGS $LDFLAGS -c *.c

# Compile programme
$CCF $CFLAGS $LDFLAGS -o $OUTEX_FILE *.o

# Move exectable to its rightful place.
mv $OUTEX_FILE data/
# Remove .o files
rm *.o


if [[ $1 == "-run" ]]; then
	cd data
	./$OUTEX_FILE
	cd ..
fi