#!/bin/sh

CCF=clang
CFLAGS='-Wall -Ofast'
HEADER='zse/ '
CFILES=''
LDFLAGS='-lncurses'
ZENGINE='zse/*'

OUTEX_FILE='z'

tar -xf data.tar

# Get All the c files
for d in $ZENGINE ; do
    if [[ -f $d ]]; then
        if [[ $d == *.c ]]; then
            CFILES="$CFILES $d"
        fi
    elif [[ -d $d ]]; then
            HEADER="$HEADER $d/"
        for subd in $d/* ; do
            if [[ $subd == *.c ]]; then
                CFILES="$CFILES $subd"
            fi
        done
    fi
done

for s in '.' ; do
    if [[ -f $s ]]; then
        if [[ $s == *.c ]]; then
            CFILES="$CFILES $s"
        fi
    fi
done


$CCF $CFLAGS -std=$1 $LDFLAGS -I"$HEADER" -c $CFILES ztorg.c
$CCF $CFLAGS $LDFLAGS -o data/$OUTEX_FILE *.o

rm -rf *.o
